//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopWebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasketInfo
    {
        public string Id { get; set; }
        public string IdBasket { get; set; }
        public string IdProduct { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual Product Product { get; set; }
    }
}
