//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopWebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public Basket()
        {
            this.BasketInfoes = new HashSet<BasketInfo>();
        }
    
        public string Id { get; set; }
        public string IdCustomer { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<BasketInfo> BasketInfoes { get; set; }
    }
}
