//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopWebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageData
    {
        public ImageData()
        {
            this.Products = new HashSet<Product>();
        }
    
        public string Id { get; set; }
        public string DisplayName { get; set; }
        public string Extension { get; set; }
        public string BaseData { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
