//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopWebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputInfo
    {
        public string Id { get; set; }
        public string IdOutput { get; set; }
        public string IdProduct { get; set; }
        public Nullable<System.DateTime> DateOutput { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<double> OutputPrice { get; set; }
        public Nullable<int> IsCheckOut { get; set; }
        public Nullable<System.DateTime> DateCheckOut { get; set; }
    
        public virtual Output Output { get; set; }
        public virtual Product Product { get; set; }
    }
}
