//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopWebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.BasketInfoes = new HashSet<BasketInfo>();
            this.Inputs = new HashSet<Input>();
            this.OutputInfoes = new HashSet<OutputInfo>();
        }
    
        public string Id { get; set; }
        public string DisplayName { get; set; }
        public string IdImageData { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public string IdCategory { get; set; }
        public string IdUnit { get; set; }
        public string Descriptions { get; set; }
    
        public virtual ICollection<BasketInfo> BasketInfoes { get; set; }
        public virtual Category Category { get; set; }
        public virtual ImageData ImageData { get; set; }
        public virtual ICollection<Input> Inputs { get; set; }
        public virtual ICollection<OutputInfo> OutputInfoes { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
