//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopWebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Baskets = new HashSet<Basket>();
            this.InputInfoes = new HashSet<InputInfo>();
            this.Outputs = new HashSet<Output>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Point { get; set; }
        public string IdUserAuthority { get; set; }
    
        public virtual ICollection<Basket> Baskets { get; set; }
        public virtual ICollection<InputInfo> InputInfoes { get; set; }
        public virtual ICollection<Output> Outputs { get; set; }
        public virtual UserAuthority UserAuthority { get; set; }
    }
}
